# Generated by Django 3.2.4 on 2021-06-11 13:28

from django.db import migrations
import user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210611_1813'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.managers.CustomUserManager()),
            ],
        ),
    ]
